CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    done BOOLEAN DEFAULT FALSE
);

INSERT INTO tasks (title)
SELECT 'task1' WHERE NOT EXISTS (SELECT 1 FROM tasks)
UNION ALL
SELECT 'task2' WHERE NOT EXISTS (SELECT 1 FROM tasks)
UNION ALL
SELECT 'task3' WHERE NOT EXISTS (SELECT 1 FROM tasks);